name: Readme - svg text
on:
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run the action
      uses: tonalmathew/readme-typing@main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        INPUT_TEXT: |
          Hi, I'm Tonal Mathew
          I'm a Full-Stack Developer
        COLOR: yellow

